#Build you squad info program here
print("Squad 8")
print("We are all resilient people")
print()
print("Our team consists of: ")
print()
print("Zeus A")
print("I'm IT technician, helping people to feel confortable with tech stuff")
print("I'm learning python to become a data scientist")
print()
print()
print("mariam k")
print("I am good at painting")
print("I want to be a data analyist")
print()
print()
print("Moradeke A")
print("I love baking")
print("I'm trying to prepare myself for college")
print()
print()
print("Peter A")
print("Eyecare physician, introvert, programmer and tech enthusiast")
print("I am learning Python because I want to build tech solutions..just build")
print()
print()
print("Rechol k")
print("I love writing poetry") 
print ("I want to be a software engineer")
print()
print()
print("Dickens A")
print("I am new in this tech field")
print("I want to learn python to solve challenges in health care")
print()
print()
print("Susan N")
print("I am a tech enthusiast, golfer, student and a programmer to be")
print("I am learning python so that I can apply python in civil Engineering🤩")
print()
print()
print("Oluwaseyifunmi A")
print("Student who loves to learn new things about tech.")
print("I want to be able to create programs that makes life easier for everyone.")
print()
print()
print("Quadri A.")
print("Tech lover and i want to be a programmer")
print("wanna learn python to beacome a software engineer")
print()
print()
print("Kachi W.")
print("I am a Nigerian and a tech enthusiast.")
print("I am learning Python to start building in relevant fields such as AI and machine learning.")
print()
print()
print()
print("Alvin O")
print("A lover of technology security in particular")
print("Looking to learn python concepts and apply the knowledge in my security journey")
print()
print()
print("Oluwatosin A.")
print("a lover of tech and mathematics")
print("looking forward to gathering much knowledge as possible in python")
print()
print()
print("Abdur-Rahman A.")
print("i'm a student of Architecture planning to switch careers to tech")
print("I am learning python as one of the languages needed in software engineering")
print()
print()
print("Abigael Chebet")
print("Iam am a backend developer from Kenya")
print("I am learning python so as to equip myself for the future.")
print()
print()
print("Omolabake Mohammed")
print("Currently studying Hospitality Management")
print("I am learning python because i want to learn it and i cant wait to start classes")
print()
print()
print("Oketoki David")
print("I am Nigerian and also a product designer")
print("I am learning python to complement my tech journey as a product designer")
print()
print()
print("Emmanuel Idowu")
print("I am Nigerian and an aspiring data scientist")
print("I am learning python to help with my tech journey as a data scientist")